name: BlueLibre AI Autobuilder — Linux

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install Python deps for autobuilder
        run: pip install requests

      - name: Install Linux build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake qtbase5-dev

      - name: Build (capture)
        id: build
        run: |
          set -euxo pipefail
          BUILD_CMD="cmake -S . -B build && cmake --build build -j"
          echo "BUILD_CMD=$BUILD_CMD" >> $GITHUB_OUTPUT
          bash -lc "$BUILD_CMD" | tee build.log
        continue-on-error: true

      - name: Attempt AI auto-fix with OpenAI
        if: steps.build.outcome != 'success'
        env:
          PROVIDER: openai
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ vars.OPENAI_MODEL || 'gpt-4.1-mini' }}
          AI_BUILDER_ATTEMPTS: "2"
          BUILD_CMD: ${{ steps.build.outputs.BUILD_CMD }}
        run: python3 tools/ai_autobuilder.py || true

      - name: Push branch with fixes (if any)
        if: steps.build.outcome != 'success'
        run: |
          set -eux
          if git diff --quiet HEAD; then exit 0; fi
          BRANCH="fix/linux-ai-autobuilder-${{ github.run_id }}"
          git config user.name "ai-autobuilder[bot]"
          git config user.email "ai-autobuilder@users.noreply.github.com"
          git switch -c "$BRANCH"
          git add -A
          git commit -m "AI autobuilder: Linux fixes" || true
          git push --set-upstream origin "$BRANCH" || true

      - name: Upload Linux build artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: |
            build/**
          if-no-files-found: ignore
