name: BlueLibre AI Autobuilder — Android (OpenAI with llama fallback)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps for autobuilder
        run: pip install requests

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Install Android SDK components
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Set up Gradle (fallback)
        uses: gradle/gradle-build-action@v2

      - name: Build (capture)
        id: build
        shell: bash
        run: |
          set -euxo pipefail
          CANDIDATES=("android/gardle/gradlew" "android/gradlew" "gradlew")
          WRAP=""
          for c in "${CANDIDATES[@]}"; do
            if [ -f "$c" ]; then WRAP="$c"; break; fi
          done
          if [ -n "$WRAP" ]; then
            chmod +x "$WRAP"
            WORKDIR="$(dirname "$WRAP")"
            [ "$WORKDIR" = "." ] || cd "$WORKDIR"
            CMD="./$(basename "$WRAP") assembleDebug --stacktrace"
          else
            CMD='gradle -p android assembleDebug --stacktrace'
          fi
          echo "BUILD_CMD=$CMD" >> "$GITHUB_OUTPUT"
          set +e
          bash -lc "$CMD" | tee build.log
          EXIT=$?
          set -e
          echo "EXIT_CODE=$EXIT" >> "$GITHUB_OUTPUT"
          [ -f build.log ] || echo "(no build output captured)" > build.log
          exit 0
        continue-on-error: true

      - name: Install llama.cpp for fallback
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential
          git clone --depth=1 https://github.com/ggerganov/llama.cpp
          cd llama.cpp && make -j
          echo "LLAMA_CPP_BIN=$PWD/main" >> $GITHUB_ENV

      - name: Attempt AI auto-fix (OpenAI → llama fallback)
        if: always() && steps.build.outputs.EXIT_CODE != '0'
        env:
          PROVIDER: openai
          FALLBACK_PROVIDER: llama
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ vars.OPENAI_MODEL || 'gpt-4o-mini' }}
          # Point MODEL_PATH to a model available in CI (upload or fetch in a prior step)
          MODEL_PATH: ${{ vars.MODEL_PATH || 'models/Llama-3-8B-Instruct.Q4_K_M.gguf' }}
          AI_BUILDER_ATTEMPTS: "2"
          BUILD_CMD: ${{ steps.build.outputs.BUILD_CMD }}
        run: python3 tools/ai_autobuilder.py || true

      - name: Push branch with fixes (if any)
        if: always() && steps.build.outputs.EXIT_CODE != '0'
        run: |
          set -eux
          if git diff --quiet HEAD; then exit 0; fi
          BRANCH="fix/android-ai-autobuilder-${{ github.run_id }}"
          git config user.name "ai-autobuilder[bot]"
          git config user.email "ai-autobuilder@users.noreply.github.com"
          git switch -c "$BRANCH"
          git add -A
          git commit -m "AI autobuilder: Android fixes" || true
          git push --set-upstream origin "$BRANCH" || true

      - name: Upload APKs (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: "**/build/outputs/**/*.apk"
          if-no-files-found: ignore
