name: BlueLibre AI Autobuilder (OpenAI, Android/Gradle)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Install Android SDK components
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: First build (capture)
        id: build
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}
        run: |
          set -euxo pipefail
          chmod +x ./gradlew || true
          BUILD_CMD="${{ vars.BUILD_CMD || './gradlew assembleDebug --stacktrace' }}"
          echo "BUILD_CMD=$BUILD_CMD" >> $GITHUB_OUTPUT
          bash -lc "$BUILD_CMD" | tee build.log
        continue-on-error: true

      - name: Attempt AI auto-fix with OpenAI
        if: steps.build.outcome != 'success'
        env:
          PROVIDER: openai
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ vars.OPENAI_MODEL || 'gpt-4.1-mini' }}
          AI_BUILDER_ATTEMPTS: "2"
          BUILD_CMD: ${{ steps.build.outputs.BUILD_CMD }}
        run: |
          python3 tools/ai_autobuilder.py || true

      - name: Push branch and open PR if changes
        if: steps.build.outcome != 'success'
        run: |
          set -eux
          if git diff --quiet HEAD; then
            echo "No changes to commit."
            exit 0
          fi
          BRANCH="fix/ai-autobuilder-${{ github.run_id }}"
          git config user.name "ai-autobuilder[bot]"
          git config user.email "ai-autobuilder@users.noreply.github.com"
          git checkout -b "$BRANCH" || git switch -c "$BRANCH"
          git add -A
          git commit -m "AI autobuilder: automated patch from CI" || true
          git push --set-upstream origin "$BRANCH" || true
