name: AirysDark-AI - Detector (bootstrap)

on:
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  detect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (no credentials)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Fetch tools.tar (ONLY here)
        run: |
          set -euxo pipefail
          mkdir -p tools
          curl -fL https://raw.githubusercontent.com/AirysDark-AI/AirysDark-AI_builder/main/tools/tools.tar -o /tmp/tools.tar
          tar -xvf /tmp/tools.tar -C tools
          ls -la tools

      - name: Run detector (generates AirysDark-AI_prob.yml + logs)
        run: |
          set -euxo pipefail
          python3 tools/AirysDark-AI_detector.py

      - name: Compose PR body with detected types
        run: |
          set -euxo pipefail
          echo "### AirysDark-AI: detector results" > pr_body.md
          echo "" >> pr_body.md
          if [ -f tools/airysdark_ai_scan.json ]; then
            echo "**Detected build types:**" >> pr_body.md
            python3 - "$PWD/tools/airysdark_ai_scan.json" >> pr_body.md <<'PY'
import json, sys, pathlib
p = pathlib.Path(sys.argv[1])
try:
    j = json.loads(p.read_text(errors="ignore"))
    types = j.get("types", [])
except Exception:
    types = []
if types:
    for t in types:
        print(f"- {t}")
else:
    print("- (none)")
PY
          else
            echo "_No detector JSON found (tools/airysdark_ai_scan.json)._" >> pr_body.md
          fi
          echo "" >> pr_body.md
          echo "**Next steps:**" >> pr_body.md
          echo "1. Edit .github/workflows/AirysDark-AI_prob.yml and set env.TARGET to the build you want (e.g. android, linux, cmake)." >> pr_body.md
          echo "2. Merge this PR." >> pr_body.md
          echo "3. Manually run the workflow 'AirysDark-AI - Probe (LLM builds workflow)' from the Actions tab." >> pr_body.md

      - name: Stage detector outputs
        id: diff
        run: |
          set -euxo pipefail
          git add -A
          if git diff --cached --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Open PR with PROB workflow
        if: steps.diff.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.BOT_TOKEN }}
          branch: ai/airysdark-ai-prob
          commit-message: chore: add AirysDark-AI_prob.yml + tools (bootstrap)
          title: AirysDark-AI: add single PROB workflow + tools
          body-path: pr_body.md
          labels: automation, ci
