name: AirysDark-AI - Detector (bootstrap)

on:
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  detect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (no credentials)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Fetch tools ONLY here (per your design). The generated PROBE/BUILD flows won’t fetch again.
      - name: Fetch tools.tar (ONLY here)
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p tools
          curl -fL "https://raw.githubusercontent.com/AirysDark-AI/AirysDark-AI_builder/main/tools/tools.tar" -o /tmp/tools.tar
          tar -xvf /tmp/tools.tar -C tools
          ls -la tools

      - name: Run detector (writes scan.json + AirysDark-AI_prob.yml + pr_body_detect.md)
        shell: bash
        run: |
          set -euxo pipefail
          python3 tools/AirysDark-AI_detector.py
          # sanity checks
          test -f tools/airysdark_ai_scan.json
          test -f .github/workflows/AirysDark-AI_prob.yml
          test -f pr_body_detect.md

      - name: Stage detector outputs
        id: diff
        shell: bash
        run: |
          set -euxo pipefail
          git add -A
          if git diff --cached --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      # PR creation uses BOT_TOKEN. (KB_PUSH_TOKEN is only used later by probe/build workflows.)
      - name: Open PR with PROBE workflow
        if: steps.diff.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.BOT_TOKEN }}
          branch: ai/airysdark-ai-prob
          commit-message: "chore: add AirysDark-AI_prob.yml + tools (bootstrap)"
          title: "AirysDark-AI: add single PROBE workflow + tools"
          body-path: pr_body_detect.md
          labels: automation, ci
