name: AirysDark-AI - Detector (bootstrap)

on:
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  detect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (no credentials)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install jq (for JSON formatting)
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Fetch tools.tar (ONLY here)
        run: |
          set -euxo pipefail
          mkdir -p tools
          curl -fL https://raw.githubusercontent.com/AirysDark-AI/AirysDark-AI_builder/main/tools/tools.tar -o /tmp/tools.tar
          tar -xvf /tmp/tools.tar -C tools
          ls -la tools

      - name: Run detector (generates AirysDark-AI_prob.yml + logs)
        run: |
          set -euxo pipefail
          python3 tools/AirysDark-AI_detector.py

      - name: Build PR body (as step output)
        id: prbody
        shell: bash
        run: |
          set -euo pipefail
          {
            echo "body<<'EOF'"
            echo "### AirysDark-AI: detector results"
            echo
            if [ -f tools/airysdark_ai_scan.json ]; then
              echo "**Detected build types:**"
              types=$(jq -r '.types[]?' tools/airysdark_ai_scan.json 2>/dev/null || true)
              if [ -n "$types" ]; then
                while IFS= read -r t; do
                  echo "- $t"
                done <<< "$types"
              else
                echo "- (none)"
              fi
            else
              echo "_No detector JSON found (tools/airysdark_ai_scan.json)._"
            fi
            echo
            echo "**Next steps:**"
            echo "1. Edit \`.github/workflows/AirysDark-AI_prob.yml\` and set **env.TARGET** (e.g. \`android\`, \`linux\`, \`cmake\`)."
            echo "2. Merge this PR."
            echo "3. Manually run **AirysDark-AI - Probe (LLM builds workflow)** from the Actions tab."
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Stage detector outputs
        id: diff
        run: |
          set -euxo pipefail
          git add -A
          if git diff --cached --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Open PR with PROB workflow
        if: steps.diff.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.BOT_TOKEN }}
          branch: "ai/airysdark-ai-prob"
          commit-message: "chore: add AirysDark-AI_prob.yml + tools (bootstrap)"
          title: "AirysDark-AI: add single PROB workflow + tools"
          body: ${{ steps.prbody.outputs.body }}
          labels: "automation, ci"
