
name: AirysDark-AI — Probe Cmake

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install requests

      - name: Ensure AirysDark-AI tools
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p tools
          BASE_URL="https://raw.githubusercontent.com/AirysDark-AI/AirysDark-AI_builder/main/tools"
          [ -f tools/AirysDark-AI_probe.py ]    || curl -fL "$BASE_URL/AirysDark-AI_probe.py"    -o tools/AirysDark-AI_probe.py
          [ -f tools/AirysDark-AI_builder.py ]  || curl -fL "$BASE_URL/AirysDark-AI_builder.py"  -o tools/AirysDark-AI_builder.py

      - name: Probe build command
        id: probe
        run: |
          set -euxo pipefail
          python3 tools/AirysDark-AI_probe.py --type "cmake" | tee /tmp/probe.out
          CMD=$(grep -E '^BUILD_CMD=' /tmp/probe.out | sed 's/^BUILD_CMD=//')
          echo "BUILD_CMD=$CMD" >> "$GITHUB_OUTPUT"

      - name: Create PR with generated final workflow
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.BOT_TOKEN }}
          branch: ai/airysdark-ai-workflow-cmake
          commit-message: "chore: add AirysDark-AI_cmake workflow (probed)"
          title: "AirysDark-AI: add cmake workflow (from probe)"
          body: |
            This PR adds the final cmake AI build workflow, generated by the probe run.
            - Probed command: ${{ steps.probe.outputs.BUILD_CMD }}
            - Next: merge this PR, then run **AirysDark-AI — Cmake (generated)**
          labels: automation, ci
