name: AirysDark-AI - Detector (bootstrap)

on:
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  detect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (no credentials)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Fetch tools.tar (ONLY here)
        run: |
          set -euxo pipefail
          mkdir -p tools
          curl -fL https://raw.githubusercontent.com/AirysDark-AI/AirysDark-AI_builder/main/tools/tools.tar -o /tmp/tools.tar
          tar -xvf /tmp/tools.tar -C tools
          ls -la tools

      - name: Run detector (generates AirysDark-AI_prob.yml + logs)
        run: |
          set -euxo pipefail
          python3 tools/AirysDark-AI_detector.py

      - name: Compose PR body
        run: |
          set -euxo pipefail
          rm -f pr_body.md
          printf "### AirysDark-AI: detector results\n\n" >> pr_body.md
          if [ -f tools/airysdark_ai_scan.json ]; then
            printf "**Detected build types:**\n" >> pr_body.md
            types=$(jq -r '.types[]?' tools/airysdark_ai_scan.json 2>/dev/null || true)
            if [ -n "$types" ]; then
              while IFS= read -r t; do
                printf -- "- %s\n" "$t" >> pr_body.md
              done <<< "$types"
            else
              printf -- "- (none)\n" >> pr_body.md
            fi
          else
            printf "_No detector JSON found (tools/airysdark_ai_scan.json)._ \n" >> pr_body.md
          fi
          printf "\n**Next steps:**\n" >> pr_body.md
          printf "1. Edit .github/workflows/AirysDark-AI_prob.yml and set env.TARGET (e.g. android, linux, cmake).\n" >> pr_body.md
          printf "2. Merge this PR.\n" >> pr_body.md
          printf "3. Manually run the workflow 'AirysDark-AI - Probe (LLM builds workflow)'.\n" >> pr_body.md

      - name: Stage detector outputs
        id: diff
        run: |
          set -euxo pipefail
          git add -A
          if git diff --cached --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Open PR with PROB workflow
        if: steps.diff.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.BOT_TOKEN }}
          branch: ai/airysdark-ai-prob
          commit-message: chore: add AirysDark-AI_prob.yml + tools (bootstrap)
          title: AirysDark-AI: add single PROB workflow + tools
          body-path: pr_body.md
          labels: automation, ci
