name: Bluelibre_AiHelper

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Bluelibre_Aihelper
        uses: AirysDark/Bluelibre_AiHelper@v1.0.0
        with:
          github_token: ${{ github.token }}
          google_api_key: ${{ secrets.GOOGLE_API_KEY }}         # optional
          openrouter_api_key: ${{ secrets.OPENROUTER_API_KEY }} # optional
